- hosts: all
#   become: true

  tasks:
  - name: create a docker image with deployed waf file
    command: docker build -t edowon0623/cicd-project-ansible .
    args: 
        chdir: /root
    
  - name: push the image on Docker Hub
    command: docker push edowon0623/cicd-project-ansible

  - name: remove the docker image from the ansible server
    command: docker rmi edowon0623/cicd-project-ansible  
    ignore_errors: yes

    